(()=>{"use strict";const A=window.GakudoApp,C=A.config,$=id=>document.getElementById(id);let last=null;const status=(m,t="ok")=>{const e=$("checkStatus");e.textContent=m;e.className=`status show ${t}`;clearTimeout(status.timer);status.timer=setTimeout(()=>e.classList.remove("show"),6000)};$("checkVersion").textContent=C.version;$("checkFacilityCode").value=C.facilityCode;$("checkFacilityLabel").textContent=C.facilityCode;$("checkClearCode").onclick=()=>{$("checkAccessCode").value="";$("checkAccessCode").focus()};$("checkDemoFill").onclick=()=>{$("checkFacilityCode").value=C.facilityCode;$("checkStaffCode").value=C.demo.managerCode;$("checkAccessCode").value=C.demo.accessCode};$("checkLoginForm").onsubmit=login;$("checkLogout").onclick=logout;$("checkRunAll").onclick=runAll;$("checkCopy").onclick=copyResult;$("checkTargetConfirmed").onchange=syncPrepare;$("checkDemoConfirm").oninput=syncPrepare;$("checkPrepareDemo").onclick=prepareDemo;if(A.getOwnerToken())restore();
async function login(e){e.preventDefault();const b=$("checkLoginButton");b.disabled=true;try{const d=await A.ownerApi("/owner/login",{method:"POST",auth:false,body:{facilityCode:$("checkFacilityCode").value.trim(),staffCode:$("checkStaffCode").value.trim(),accessCode:$("checkAccessCode").value}});A.setOwnerToken(d.token);showApp(d);await runAll()}catch(x){status(x.message,"error")}finally{b.disabled=false}}
async function restore(){try{const d=await A.ownerApi("/auth/me");if(!["owner","manager","leader"].includes(d.staff?.role))throw new Error("管理者権限が必要です。");showApp(d);await runAll()}catch(x){A.setOwnerToken("");status(x.message||"ログインし直してください。","error")}}
function showApp(d){const s=d.staff||d.auth?.staff||{},f=d.facility||d.auth?.facility||{};$("checkOperator").textContent=s.display_name||s.displayName||s.staff_code||s.staffCode||"管理者";$("checkOperatorMeta").textContent=`${s.staff_code||s.staffCode||""}／${f.facility_name||f.facilityName||C.facilityName}`;$("checkLogin").classList.add("hidden");$("checkApp").classList.remove("hidden")}
async function logout(){try{await A.ownerApi("/auth/logout",{method:"POST"})}catch{}A.setOwnerToken("");location.reload()}
async function test(id,label,fn,judge){const t=performance.now();try{const data=await fn();const ok=judge?Boolean(judge(data)):true;return{id,label,status:ok?"pass":"fail",detail:ok?`正常（${Math.round(performance.now()-t)}ms）`:"応答内容が期待値と一致しません。",data}}catch(x){return{id,label,status:"fail",detail:`${x.status||x.data?.code||"ERROR"}：${x.message}`}}}
async function runAll(){const b=$("checkRunAll");b.disabled=true;status("GAKUDO-1〜10と公開17ファイルを検査しています…","info");const checks=[];let health=null,full=null;try{health=await test("worker_health","Worker健康診断",()=>rawApi("/health"),d=>d.ok&&d.version==="GAKUDO-10-WORKER-FINAL-20260802"&&d.finalCheckOk);checks.push(health);checks.push(await test("worker_version","最終Worker・リリース",()=>rawApi("/version"),d=>d.version==="GAKUDO-10-WORKER-FINAL-20260802"&&d.release==="GAKUDO-10-FINAL-20260802"&&d.finalRelease===true&&d.publicFilesExpected===17));checks.push(await test("public_config","公開設定",()=>rawApi("/public-config"),d=>d.systemCode==="GAKUDO"&&d.facility?.facilityCode===C.facilityCode));checks.push(await test("owner_session","管理者セッション",()=>A.ownerApi("/auth/me"),d=>d.ok&&["owner","manager","leader"].includes(d.staff?.role)));checks.push(await test("owner_dashboard","管理者ダッシュボードAPI",()=>A.ownerApi("/admin/dashboard"),d=>d.ok));checks.push(await test("staff_today","スタッフ当日API",()=>A.ownerApi("/staff/today"),d=>d.ok));checks.push(await test("family_dashboard","児童・保護者台帳API",()=>A.ownerApi("/staff/families?limit=20"),d=>d.ok));checks.push(await test("capacity_dashboard","長期休暇・定員API",()=>A.ownerApi("/admin/holiday-capacity"),d=>d.ok));checks.push(await test("notification_dashboard","通知・警告API",()=>A.ownerApi("/admin/notifications?status=open&limit=30"),d=>d.ok));full=await test("database_full","DB・RLS・全機能20項目検査",()=>A.ownerApi("/admin/system-check"),d=>d.ok&&d.database?.ok&&d.database?.summary?.fail===0);checks.push(full);checks.push(...await staticChecks());checks.push(...await guardianChecks());checks.push(...await negativeChecks());last={ok:checks.every(x=>x.status!=="fail"),checks,health:health?.data||null,database:full?.data?.database||null,checkedAt:new Date().toISOString()};render(last);status(last.ok?"一括検査が完了しました。失敗0件です。":"一括検査で失敗が見つかりました。",""+(last.ok?"ok":"error"))}finally{b.disabled=false}}
async function rawApi(path,options={}){const r=await fetch(C.apiBase+path,{cache:"no-store",...options});const d=await r.json().catch(()=>({}));if(!r.ok)throw Object.assign(new Error(d.message||"処理できませんでした。"),{status:r.status,data:d});return d}
async function staticChecks(){const files=["index.html", "member.html", "staff.html", "owner.html", "owner-ipad.html", "system-check.html", "styles.css", "owner.css", "owner-ipad.css", "system-check.css", "common.js", "config.js", "member.js", "staff.js", "owner.js", "owner-ipad.js", "system-check.js"];const out=[];for(const f of files)out.push(await test(`file_${f}`,`公開ファイル：${f}`,async()=>{const r=await fetch(f,{cache:"no-store"});return{ok:r.ok,status:r.status}},d=>d.ok));return out}
async function guardianChecks(){const out=[];let token="";try{const d=await rawApi("/member/login",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({facilityCode:C.facilityCode,lineUserId:C.demo.lineUserId,phone:C.demo.phone})});token=d.token||"";out.push({id:"guardian_login",label:"保護者デモログイン",status:token?"pass":"fail",detail:token?"正常":"トークン未取得"});const h={Authorization:`Bearer ${token}`};out.push(await test("guardian_portal","保護者ポータルAPI",()=>rawApi("/member/portal",{headers:h}),x=>x.ok));out.push(await test("guardian_holiday","長期休暇申請情報API",()=>rawApi("/member/holiday",{headers:h}),x=>x.ok))}catch(x){out.push({id:"guardian_login",label:"保護者デモログイン",status:"fail",detail:x.message})}finally{if(token)try{await rawApi("/member/logout",{method:"POST",headers:{Authorization:`Bearer ${token}`}})}catch{}}return out}
async function negativeChecks(){const out=[];out.push(await expected("unauthorized","未認証の管理者API拒否","/admin/system-check",{},401));out.push(await expected("unknown_api","存在しないAPIの404","/gakudo-final-not-found",{},404));out.push(await expected("demo_guard","デモ準備の二重確認ガード","/admin/demo-prepare",{method:"POST",headers:{Authorization:`Bearer ${A.getOwnerToken()}`,"Content-Type":"application/json"},body:JSON.stringify({confirm:""})},400));return out}
async function expected(id,label,path,options,code){try{const r=await fetch(C.apiBase+path,options);return{id,label,status:r.status===code?"pass":"fail",detail:r.status===code?`HTTP ${code}で正常拒否`:`期待 ${code}／実際 ${r.status}`}}catch(x){return{id,label,status:"fail",detail:x.message}}}
function render(r){const db=(r.database?.checks||[]).map(x=>({id:`db_${x.id}`,label:`DB：${x.label}`,status:x.status,detail:JSON.stringify(x.detail)}));const all=[...r.checks,...db];const pass=all.filter(x=>x.status==="pass").length,fail=all.filter(x=>x.status==="fail").length,warn=all.filter(x=>x.status==="warn").length;$("checkTotal").textContent=all.length;$("checkPass").textContent=pass;$("checkFail").textContent=fail;$("checkWarn").textContent=warn;$("checkWorkerVersion").textContent=r.health?.version||"-";$("checkRelease").textContent=r.health?.release||"-";$("checkDbVersion").textContent=r.database?.version||"-";$("checkCron").textContent=`${r.health?.recommendedCronUtc||"-"}／${r.health?.notificationDeliveryMode||"-"}`;$("checkTime").textContent=`最終検査：${new Date(r.checkedAt).toLocaleString("ja-JP")}`;const o=$("checkOverall");o.className=`overall ${fail?"fail":warn?"warn":"pass"}`;o.textContent=fail?`失敗 ${fail}件`:warn?`合格（注意 ${warn}件）`:"すべて合格";$("checkList").innerHTML=all.map(x=>`<article class="check-item ${A.esc(x.status)}"><div class="check-item-head"><div class="check-item-title">${A.esc(x.label)}</div><span class="check-state">${x.status==="pass"?"合格":x.status==="warn"?"注意":"失敗"}</span></div><div class="check-detail">${A.esc(x.detail||"")}</div></article>`).join("");$("checkRaw").textContent=JSON.stringify(r,null,2)}
function syncPrepare(){$("checkPrepareDemo").disabled=!($("checkTargetConfirmed").checked&&$("checkDemoConfirm").value.trim()==="DEMO")}
async function prepareDemo(){if(!confirm("デモ施設の基本データを今日の日付へ再準備しますか。"))return;const b=$("checkPrepareDemo");b.disabled=true;try{const r=await fetch(C.apiBase+"/admin/demo-prepare",{method:"POST",headers:{Authorization:`Bearer ${A.getOwnerToken()}`,"Content-Type":"application/json","X-DPRO-Confirm":"DEMO"},body:JSON.stringify({confirm:"DEMO"})});const d=await r.json();if(!r.ok)throw new Error(d.message||"デモ準備に失敗しました。");status("デモ基本データを準備しました。自動再検査します。","ok");$("checkDemoConfirm").value="";$("checkTargetConfirmed").checked=false;syncPrepare();await runAll()}catch(x){status(x.message,"error")}finally{syncPrepare()}}
async function copyResult(){if(!last)return status("先に一括検査を実行してください。","error");const text=`DPRO GAKUDO SYSTEM CHECK
${new Date(last.checkedAt).toLocaleString("ja-JP")}
検査件数: ${$("checkTotal").textContent}
合格: ${$("checkPass").textContent}
失敗: ${$("checkFail").textContent}
注意: ${$("checkWarn").textContent}

${JSON.stringify(last,null,2)}`;try{await navigator.clipboard.writeText(text);status("検査結果をコピーしました。","ok")}catch{status("コピーできませんでした。JSON表示からコピーしてください。","error")}}
})();