(()=>{"use strict";
const DATA={"version":"GAKUDO-R4-20260826","steps":[{"id":"F10-01","title":"4つの役割画面を知る","role":"public","route":"index.html","targets":[".hero-copy",".buttons","a[href='member.html']"],"copy":"このシステムは保護者・スタッフ・管理者PC・管理者iPadの4画面で役割を分けています。"},{"id":"F10-02","title":"保護者ポータルの入口","role":"guardian","route":"member.html","targets":["#portal .profile","#guardianName","#children"],"copy":"保護者画面では、児童ごとの利用予定とお迎え方法を最初に確認します。"},{"id":"F10-03","title":"児童・利用予定を確認","role":"guardian","route":"member.html","targets":["#children",".child-card",".plan"],"copy":"児童ごとの予定、退室時刻、退室方法、お迎え情報を確認できます。"},{"id":"F10-04","title":"欠席・利用変更の場所","role":"guardian","route":"member.html","targets":["#changeForm","#changeType","#changeDate"],"copy":"欠席、利用追加、入退室時刻・退室方法の変更はこの欄から申請します。"},{"id":"F10-05","title":"お迎え変更と代理お迎え","role":"guardian","route":"member.html","targets":["#pickupForm","#pickupMethod","#pickupPersonField"],"copy":"お迎え方法の変更と、登録済み代理お迎え者の指定はこの欄で行います。"},{"id":"F10-06","title":"長期休暇と空き状況","role":"guardian","route":"member.html","targets":["#holidayPeriods","#holidayDates","#holidayApplications"],"copy":"長期休暇は対象期間、空き状況、申請状況をまとめて確認できます。"},{"id":"F10-07","title":"スタッフ当日画面","role":"staff","route":"staff.html","targets":["#staffSummary","#staffChildren","#staffFilter"],"copy":"スタッフ画面では、本日の児童、入退室状態、お迎え方法、安全警告を一覧で確認します。"},{"id":"F10-08","title":"申し送りと安全確認","role":"staff","route":"staff.html","targets":["#staffHandoffs","#openHandoffForm","#openIncidentForm"],"copy":"申し送りと事故・ヒヤリハットは同じ当日画面から確認・登録できます。"},{"id":"F10-09","title":"管理者iPadで全体を俯瞰","role":"owner_ipad","route":"owner-ipad.html","targets":["#ipadSummary",".ipad-tabs","#ipadPendingPreview","#ipadAlertChildren"],"copy":"管理者iPadは当日の全体状況、承認待ち、安全情報を大きなタッチ画面で確認します。"},{"id":"F10-10","title":"管理PCで施設全体を管理","role":"owner","route":"owner.html","targets":[".owner-nav","#ownerSummary","#viewCapacity","#viewNotifications"],"copy":"管理PCでは申請承認、児童台帳、長期休暇・定員、通知・警告、安全、職員権限、操作履歴を管理します。"}],"categories":[{"id":"GC-01","title":"はじめに・画面と役割","topics":["4画面の役割","デモの開き方","個人情報を入れない"]},{"id":"GC-02","title":"保護者の利用予定・変更","topics":["利用予定","欠席・利用変更","お迎え変更","代理お迎え","一人帰り"]},{"id":"GC-03","title":"長期休暇","topics":["期間確認","空き/満員/停止","利用申請","申請状況"]},{"id":"GC-04","title":"スタッフ当日運用","topics":["本日の児童","入室","お迎え待ち","退室","本人確認","日常確認"]},{"id":"GC-05","title":"申し送り・事故安全","topics":["申し送り","アレルギー注意","事故・ヒヤリハット","安全警告"]},{"id":"GC-06","title":"管理者の承認","topics":["欠席/利用変更承認","お迎え変更承認","一人帰り承認","LINE連携"]},{"id":"GC-07","title":"定員・待機・施設管理","topics":["児童台帳","長期休暇期間","日別定員","待機","職員権限","操作履歴"]},{"id":"GC-08","title":"通知・警告","topics":["入退室超過","申請期限","通知キュー","警告対応","自動確認の意味"]}]};
const KEY="dpro_tutorial_gakudo_v1_1";
const HOSTS=new Set(["index.html","member.html","staff.html","owner.html","owner-ipad.html"]);
const ROLE_BY_PAGE={"index.html":"public","member.html":"guardian","staff.html":"staff","owner.html":"owner","owner-ipad.html":"owner_ipad"};
const ROLE_RELEVANCE={public:["GC-01"],guardian:["GC-01","GC-02","GC-03"],staff:["GC-01","GC-04","GC-05"],owner_ipad:["GC-04","GC-05","GC-06","GC-08"],owner:["GC-01","GC-06","GC-07","GC-08"]};
let state={step:0,status:"idle",x:null,y:null,version:DATA.version};let layer=null,card=null,hi=null,drag=null;
const page=()=>location.pathname.split("/").pop()||"index.html";
function load(){try{const s=JSON.parse(localStorage.getItem(KEY)||"null");if(s&&s.version===DATA.version)state={...state,...s}}catch(_e){}}
function save(){try{localStorage.setItem(KEY,JSON.stringify({step:state.step,status:state.status,x:state.x,y:state.y,version:DATA.version}))}catch(_e){}}
function safeRoute(r){const f=String(r||"index.html").split("?")[0];return HOSTS.has(f)?f:"index.html"}
function goForStep(i){const r=safeRoute(DATA.steps[i].route);if(page()!==r){state.step=i;state.status="active";save();location.assign(r+"?tutorial=1");return true}return false}
function findTarget(st){for(const sel of st.targets||[]){try{const el=document.querySelector(sel);if(el&&el.getClientRects().length)return el}catch(_e){}}return null}
function clearHi(){if(hi)hi.remove();hi=null}
function highlight(st){clearHi();const el=findTarget(st);if(!el)return false;const r=el.getBoundingClientRect();hi=document.createElement("div");hi.className="dpt-gakudo-highlight";Object.assign(hi.style,{left:Math.max(2,r.left-5)+"px",top:Math.max(2,r.top-5)+"px",width:Math.max(4,r.width+10)+"px",height:Math.max(4,r.height+10)+"px"});document.body.appendChild(hi);return true}
function clamp(x,y){if(!card)return{x,y};const r=card.getBoundingClientRect(),p=8;return{x:Math.max(p,Math.min(x,innerWidth-r.width-p)),y:Math.max(p,Math.min(y,innerHeight-r.height-p))}}
function setPos(x,y){if(!card)return;const p=clamp(x,y);card.style.left=p.x+"px";card.style.top=p.y+"px";card.style.right="auto";card.style.bottom="auto";state.x=p.x;state.y=p.y;save()}
function close(pause=true){clearHi();if(layer)layer.remove();layer=card=null;drag=null;if(pause&&state.status==="active"){state.status="paused";save()}}
function render(){if(!card)return;const st=DATA.steps[state.step];const found=highlight(st);card.querySelector("[data-step]").textContent=`STEP ${state.step+1} / 10 · ${st.id}`;card.querySelector("h3").textContent=st.title;card.querySelector("[data-copy]").textContent=st.copy;card.querySelector("[data-note]").textContent=found?"対象位置をハイライトしています。":"この画面では対象が見つからないため、説明だけで続けられます。";card.querySelector("[data-back]").disabled=state.step===0;card.querySelector("[data-next]").textContent=state.step===9?"完了":"次へ";card.querySelector(".dpt-gakudo-progress i").style.width=((state.step+1)*10)+"%";state.status="active";save()}
function open(start){load();if(Number.isInteger(start))state.step=Math.max(0,Math.min(9,start));if(goForStep(state.step))return;close(false);layer=document.createElement("div");layer.className="dpt-gakudo-layer";layer.innerHTML=`<section class="dpt-gakudo-card" role="dialog" aria-label="DPRO First10"><div class="dpt-gakudo-handle" tabindex="0"><strong>DPRO First10</strong><span>ここをドラッグ</span></div><div class="dpt-gakudo-progress"><i></i></div><div class="dpt-gakudo-body"><small data-step></small><h3></h3><p data-copy></p><div class="dpt-gakudo-safe">説明・ナビゲーション専用。保存・送信・承認などの業務操作は実行しません。</div><div class="dpt-gakudo-note" data-note></div></div><div class="dpt-gakudo-actions"><button data-back>戻る</button><button class="primary" data-next>次へ</button><button data-skip>スキップ</button><button data-close>閉じる</button></div></section>`;document.body.appendChild(layer);card=layer.querySelector(".dpt-gakudo-card");if(Number.isFinite(state.x)&&Number.isFinite(state.y))setPos(state.x,state.y);const h=card.querySelector(".dpt-gakudo-handle");h.addEventListener("pointerdown",e=>{if(e.button!==undefined&&e.button!==0)return;if(e.target.closest("button,a,input,select,textarea,label"))return;const r=card.getBoundingClientRect();drag={id:e.pointerId,dx:e.clientX-r.left,dy:e.clientY-r.top};h.setPointerCapture?.(e.pointerId);e.preventDefault()});h.addEventListener("pointermove",e=>{if(!drag||drag.id!==e.pointerId)return;setPos(e.clientX-drag.dx,e.clientY-drag.dy)});const stop=()=>drag=null;h.addEventListener("pointerup",stop);h.addEventListener("pointercancel",stop);h.addEventListener("keydown",e=>{if(!e.shiftKey)return;const r=card.getBoundingClientRect(),n=12;if(e.key==="ArrowLeft")setPos(r.left-n,r.top);else if(e.key==="ArrowRight")setPos(r.left+n,r.top);else if(e.key==="ArrowUp")setPos(r.left,r.top-n);else if(e.key==="ArrowDown")setPos(r.left,r.top+n);else return;e.preventDefault()});card.querySelector("[data-back]").onclick=()=>{if(state.step>0){state.step--;save();if(!goForStep(state.step))render()}};card.querySelector("[data-next]").onclick=()=>{if(state.step<9){state.step++;save();if(!goForStep(state.step))render()}else{state.status="done";save();close(false);openGuide()}};card.querySelector("[data-skip]").onclick=()=>{state.step=9;state.status="done";save();close(false);openGuide()};card.querySelector("[data-close]").onclick=()=>close(true);render()}
function currentRole(){return ROLE_BY_PAGE[page()]||"public"}
function openGuide(){close(false);document.getElementById("dpt-gakudo-guide")?.remove();const role=currentRole(),rel=new Set(ROLE_RELEVANCE[role]||[]);const g=document.createElement("section");g.id="dpt-gakudo-guide";g.setAttribute("role","dialog");g.setAttribute("aria-modal","true");g.innerHTML=`<div class="dpt-gakudo-guide-head"><div><strong>DPRO TUTORIAL</strong><h2>GAKUDO Guide Center</h2><p>現在の画面: ${role}</p></div><button data-gclose>閉じる</button></div><div class="dpt-gakudo-guide-grid">${DATA.categories.map(c=>`<article class="${rel.has(c.id)?"relevant":""}"><small>${c.id}</small><h3>${c.title}</h3><ul>${c.topics.map(t=>`<li>${t}</li>`).join("")}</ul></article>`).join("")}</div><div class="dpt-gakudo-guide-foot"><button class="primary" data-replay>First10を最初から</button><button data-resume>First10を再開</button></div>`;document.body.appendChild(g);g.querySelector("[data-gclose]").onclick=()=>g.remove();g.querySelector("[data-replay]").onclick=()=>{g.remove();state.step=0;state.status="idle";save();open(0)};g.querySelector("[data-resume]").onclick=()=>{g.remove();open(state.status==="done"?0:state.step)}}
function install(){if(page()==="system-check.html"||!HOSTS.has(page()))return;if(document.getElementById("dpt-gakudo-launch"))return;load();const b=document.createElement("button");b.id="dpt-gakudo-launch";b.textContent=state.status==="paused"?"操作ガイドを再開":"操作ガイド";b.onclick=()=>open(state.status==="done"?0:state.step);document.body.appendChild(b);const g=document.createElement("button");g.id="dpt-gakudo-guide-launch";g.textContent="Guide Center";g.onclick=openGuide;document.body.appendChild(g);if(new URLSearchParams(location.search).get("tutorial")==="1"&&state.status==="active")setTimeout(()=>open(state.step),80)}
addEventListener("resize",()=>{if(card){const r=card.getBoundingClientRect();setPos(r.left,r.top);highlight(DATA.steps[state.step])}});document.addEventListener("keydown",e=>{if(e.key!=="Escape")return;const g=document.getElementById("dpt-gakudo-guide");if(g)g.remove();else if(card)close(true)});if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",install);else install();window.DPROGakudoTutorial={open,openGuide,replay:()=>{state.step=0;state.status="idle";save();open(0)}};
})();
